[versions]
agp = "8.2.2"
commonsCodec = "1.16.0"
constraintlayout = "2.1.4"
coreKtx = "1.12.0"
kotlin = "1.9.0"
kotlinReflect = "1.9.10"
kotlinxCoroutinesCoreJvm = "1.7.3"
okhttp = "4.12.0"
recyclerview = "1.3.2"

[libraries]
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commonsCodec" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }
kotlinx-coroutines-core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinxCoroutinesCoreJvm" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[plugins]
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

